---
kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - pwd
  - sleep 15s
  - git clone http://gitea:3000/${DRONE_REPO}.git .
  - git checkout $DRONE_COMMIT

- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: build
  image: golang:alpine
  commands:
  - go test
  - go build

- name: package
  image: golang:alpine
  commands:
  - apk update
  - apk add zip git
  - mkdir -p testorepo/bin
  - go build -o testorepo/bin/saludeyshon
  - zip -r testorepo-$(git describe --tags).zip testorepo/
  - echo $(git describe --tags) > title.txt
  when:
    event: tag

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_api_key
    base_url: http://gitea:3000
    files:
    - testorepo*zip
    title: title.txt
  when:
    event: tag
