---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: golang:alpine
  commands:
  - go test
  - go build -x -o saludeyshon

- name: gitea_release
  image: plugins/gitea-release
  commands:
  - pwd
  - ls -al
  settings:
    api_key:
      from_secret: gitea_api_key
    base_url: http://gitea:3000
    checksum:
      - md5
      - sha1
    files:
    - saludeyshon
  when:
    event: tag
