---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: golang:alpine
  commands:
  - go test
  - mkdir bin
  - go build -x -o bin/saludeyshon
  - ls -al bin/

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_api_key
    base_url: http://gitea:3000
    checksum:
      - md5
      - sha1
    files:
    - bin/*
  when:
    event: tag
