---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: golang:alpine
  commands:
  - go test
  - mkdir -p testorepo/bin
  - go build -o testorepo/bin/saludeyshon
  - tar -czf xyz.tar.gz testorepo/*

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_api_key
    base_url: http://gitea:3000
    checksum:
      - md5
      - sha1
    files:
    - xyz.tar.gz
  when:
    event: tag
