---
kind: pipeline
type: kubernetes
name: default

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: build
  image: golang:alpine
  commands:
  - apk update
  - apk add zip git
  - mkdir -p testorepo/bin
  - go build -o testorepo/bin/saludeyshon
  - zip -r testorepo-$(git describe --tags).zip testorepo/

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_api_key
    base_url: http://gitea:3000
    checksum:
      - md5
      - sha1
    files:
    - testorepo*
  when:
    event: tag
